### Test with AutoGluon

In [1]:
import pandas as pd
import numpy as np
print("numpy version:", np.__version__) # 1.6.2 needed for autogluon
from autogluon.tabular import TabularPredictor
from scipy.stats import spearmanr
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

numpy version: 1.26.4

c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
transactions = pd.read_csv(r"original_data\transactions_2016_2017.csv")
train_labels = pd.read_csv(r"original_data\customer_clv_train.csv")
test_labels =  pd.read_csv(r"original_data\customer_clv_test.csv")

C:\Users\Marte\AppData\Local\Temp\ipykernel_14064\2056241763.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions = pd.read_csv(r"C:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\data\original_data\transactions_2016_2017.csv")

In [3]:
transactions.shape
transactions["cust_id"].nunique() # 145 739 unieke klanten

145739

In [ ]:
features = pd.read_csv(r"data\features_enriched.csv")
features.shape # 145 739 rijen (komt overeen met aantal unieke klanten in transactions)
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145739 entries, 0 to 145738
Data columns (total 87 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   cust_id                                145739 non-null  object
 1   n_items                                145739 non-null  int64
 2   n_sales                                145739 non-null  int64
 3   n_returns                              145739 non-null  int64
 4   first_purchase                         145739 non-null  object
 5   last_purchase                          145739 non-null  object
 6   n_items_non_returned                   145739 non-null  float64
 7   n_sales_non_returned                   145739 non-null  float64
 8   total_revenue_net                      145739 non-null  float64
 9   total_discount                         145739 non-null  float64
 10  total_revenue_gross                    145739 non-null  float64
 11  customer_lifetime_days                 145739 non-null  int64
 12  recency_days                           145739 non-null  int64
 13  avg_rev_per_item                       145739 non-null  float64
 14  avg_rev_per_sale                       145739 non-null  float64
 15  return_rate                            145739 non-null  float64
 16  discount_ratio                         145739 non-null  float64
 17  avg_days_between_purchases             145739 non-null  float64
 18  monetary_per_item                      145739 non-null  float64
 19  days_since_last_purchase               145739 non-null  int64
 20  days_since_last_vs_avg                 145739 non-null  float64
 21  days_from_first_purchase_to_reference  145739 non-null  int64
 22  recency_ratio                          145739 non-null  float64
 23  purchase_frequency                     145739 non-null  float64
 24  items_per_sale                         145739 non-null  float64
 25  avg_days_between_orders                145739 non-null  float64
 26  std_days_between_orders                145739 non-null  float64
 27  min_days_between_orders                145739 non-null  float64
 28  max_days_between_orders                145739 non-null  float64
 29  avg_days_to_pack                       145739 non-null  float64
 30  std_days_to_pack                       145739 non-null  float64
 31  max_days_to_pack                       145739 non-null  float64
 32  top_brand_share                        145739 non-null  float64
 33  n_unique_brands                        145739 non-null  int64
 34  n_unique_products                      145739 non-null  int64
 35  top_color_share                        145739 non-null  float64
 36  n_unique_colors                        145739 non-null  int64
 37  prod_type_1_dominant_share             145739 non-null  float64
 38  prod_type_1_n_unique                   145739 non-null  int64
 39  prod_type_3_dominant_share             145739 non-null  float64
 40  prod_type_3_n_unique                   145739 non-null  int64
 41  prod_type_4_dominant_share             145739 non-null  float64
 42  prod_type_4_n_unique                   145739 non-null  float64
 43  prod_type_5_dominant_share             145739 non-null  float64
 44  prod_type_5_n_unique                   145739 non-null  float64
 45  share_web_only                         145739 non-null  float64
 46  share_web_only_non_returned            145739 non-null  float64
 47  size_mean                              145739 non-null  float64
 48  size_std                               145739 non-null  float64
 49  size_min                               145739 non-null  float64
 50  size_max                               145739 non-null  float64
 51  size_median                            145739 non-null  float64
 52  size_n_unique                          145739 non-null  int64
 53  top_season_share                       145739 non-null  float64
 54  n_unique_seasons                       145739 non-null  int64
 55  share_outlet                           145739 non-null  float64
 56  share_outlet_non_returned              145739 non-null  float64
 57  avg_discount_per_item                  145739 non-null  float64
 58  max_discount_per_item                  145739 non-null  float64
 59  share_discounted_items                 145739 non-null  float64
 60  avg_discount_per_sale                  145739 non-null  float64
 61  avg_sale_discount_ratio                145739 non-null  float64
 62  avg_items_per_sale                     145739 non-null  float64
 63  revenue_last_90d                       145739 non-null  float64
 64  avg_revenue_per_day_last_90d           145739 non-null  float64
 65  observation_days_total                 145739 non-null  int64
 66  avg_revenue_per_day_total              145739 non-null  float64
 67  revenue_velocity                       145739 non-null  float64
 68  n_brands_returned                      145739 non-null  float64
 69  returned_revenue_sum                   145739 non-null  float64
 70  prod_heel_dominant_share               145739 non-null  float64
 71  prod_heel_n_unique                     145739 non-null  float64
 72  prod_material_dominant_share           145739 non-null  float64
 73  prod_material_n_unique                 145739 non-null  float64
 74  prod_insole_dominant_share             145739 non-null  float64
 75  prod_insole_n_unique                   145739 non-null  float64
 76  prod_print_dominant_share              145739 non-null  float64
 77  prod_print_n_unique                    145739 non-null  float64
 78  prod_comfort_sole_dominant_share       145739 non-null  float64
 79  prod_comfort_sole_n_unique             145739 non-null  float64
 80  prod_comfort_wear_dominant_share       145739 non-null  float64
 81  prod_comfort_wear_n_unique             145739 non-null  float64
 82  prod_clasp_dominant_share              145739 non-null  float64
 83  prod_clasp_n_unique                    145739 non-null  float64
 84  prob_alive                             145739 non-null  float64
 85  pred_num_purchases                     145739 non-null  float64
 86  expected_avg_sales                     145739 non-null  float64
dtypes: float64(69), int64(15), object(3)
memory usage: 96.7+ MB

In [6]:
print(train_labels.head())
print(test_labels.head())

            cust_id  revenue_2018_2019
0  klantwj2374mzmab             209.85
1  a63atwr2ig2jfprr              82.93
2  zr7ihbfbi6gcy2tz              89.95
3  dt7cthjqnjmkbiu6               0.00
4  etcrrgcbrzfovyzj               0.00
            cust_id
0  2dfoualegmpt6x2h
1  d2q2stjpnzld7a4r
2  cojscuqlpylhclv2
3  vntezlhi2ryvxk6m
4  jgy4ytjkdr2b75wf

In [7]:
# Mergen met revenue 2018-2019 (om de target variable te hebben)
master_train = train_labels.merge(features, on="cust_id", how="left").fillna(0) #train labels als basis 
master_train.head()

,cust_id,revenue_2018_2019,n_items,n_sales,n_returns,first_purchase,last_purchase,n_items_non_returned,n_sales_non_returned,total_revenue_net,...,prod_print_n_unique,prod_comfort_sole_dominant_share,prod_comfort_sole_n_unique,prod_comfort_wear_dominant_share,prod_comfort_wear_n_unique,prod_clasp_dominant_share,prod_clasp_n_unique,prob_alive,pred_num_purchases,expected_avg_sales
0,klantwj2374mzmab,209.85,2,1,1,2016-01-01,2016-01-01,1.0,1.0,83.30,...,0.0,0.0,0.0,0.0,0.0,0.500000,2.0,1.000000,0.011254,0.000000
1,a63atwr2ig2jfprr,82.93,4,2,3,2016-01-01,2017-06-21,1.0,1.0,53.96,...,1.0,0.0,0.0,1.0,1.0,0.666667,2.0,0.724322,0.026478,63.250871
2,zr7ihbfbi6gcy2tz,89.95,2,2,0,2016-01-01,2017-01-27,2.0,2.0,83.70,...,0.0,1.0,1.0,1.0,1.0,0.500000,2.0,0.658666,0.024078,48.008387
3,dt7cthjqnjmkbiu6,0.00,4,2,1,2016-01-01,2017-05-24,3.0,2.0,350.92,...,0.0,0.0,0.0,0.0,0.0,0.500000,3.0,0.713269,0.026074,310.739524
4,etcrrgcbrzfovyzj,0.00,6,2,3,2016-01-01,2017-01-28,3.0,2.0,144.50,...,0.0,0.0,0.0,0.0,0.0,1.000000,1.0,0.659199,0.024097,72.016934

In [8]:
# Splits het VOLLEDIGE dataframe
train_set, val_set = train_test_split(
    master_train,                  # Hier geef je de hele tabel mee (77 kolommen)
    test_size=0.2, 
    random_state=42,
    stratify=(master_train["revenue_2018_2019"] > 0)
)

# Nu bevatten train_set en val_set allebei 77 kolommen
print(f"Train set vorm: {train_set.shape}")
print(f"Validation set vorm: {val_set.shape}")

Train set vorm: (93272, 88)
Validation set vorm: (23319, 88)

In [9]:
# Test set voorbereiden (features mergen met test_labels)
test_set_final = test_labels.merge(features, on="cust_id", how="left").fillna(0)

# Bewaar de cust_id's voor later (die heb je nodig voor je submission file)
test_cust_ids = test_set_final["cust_id"]

# Verwijder kolommen die het model niet mag zien (zoals de ID en de target kolom als die er per ongeluk in zit)
X_test_ag = test_set_final.drop(columns=["cust_id", "revenue_2018_2019"], errors="ignore")

In [10]:
train_ag = train_set.drop(columns=["cust_id"]).copy()
val_ag = val_set.drop(columns=["cust_id"]).copy()

In [11]:
# 3. INITIALISEER EN FIT IN ÉÉN KEER
# We gebruiken 'path' om de unieke map te forceren
predictor = TabularPredictor(
    label="revenue_2018_2019", 
    eval_metric="mean_absolute_error",
).fit(
    train_data=train_ag,
    tuning_data=val_ag,
    use_bag_holdout=True,  # We hebben al een aparte validation set, dus we hoeven geen extra holdout set te maken
    presets="best_quality",
    time_limit= 600  # 10 minuten
)

# 4. Toon het resultaat om te zien of het gelukt is
print(predictor.leaderboard(val_ag))

No path specified. Models will be saved in: "AutogluonModels\ag-20260425_082456"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.2
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          12
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.02 GB / 15.72 GB (19.2%)
Disk Space Avail:   151.49 GB / 475.28 GB (31.9%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to False. Reason: Skip dynamic_stacking when use_bag_holdout is enabled. (use_bag_holdout=True)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_082456"
Train Data Rows:    93272
Train Data Columns: 86
Tuning Data Rows:    23319
Tuning Data Columns: 86
Label Column:       revenue_2018_2019
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (1197.94, 0.0, 70.45545, 144.51507)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3007.90 MB
	Train Data (Original)  Memory Usage: 87.84 MB (2.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 2): ['monetary_per_item', 'avg_items_per_sale']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 2 | ['monetary_per_item', 'avg_items_per_sale']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                        : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('object', ['datetime_as_object']) :  2 | ['first_purchase', 'last_purchase']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                  : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('int', ['datetime_as_int']) : 10 | ['first_purchase', 'first_purchase.year', 'first_purchase.month', 'first_purchase.day', 'first_purchase.dayofweek', ...]
	1.9s = Fit runtime
	84 features in original data used to generate 92 features in processed data.
	Train Data (Processed) Memory Usage: 81.84 MB (2.7% of available memory)
Data preprocessing and feature engineering runtime = 2.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 398.47s of the 597.84s of remaining time.
Will use sequential fold fitting strategy because import of ray failed. Reason: ray is required to train folds in parallel for TabularPredictor or HPO for MultiModalPredictor. A quick tip is to install via `pip install "ray>=2.43.0,<2.53.0"`
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-76.458	 = Validation score   (-mean_absolute_error)
	40.59s	 = Training   runtime
	1.22s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 352.87s of the 552.24s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-76.5369	 = Validation score   (-mean_absolute_error)
	32.05s	 = Training   runtime
	0.93s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 318.80s of the 518.17s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.0 GB
	Warning: Reducing model 'n_estimators' from 300 -> 226 due to low memory. Expected memory usage reduced from 19.82% -> 15.0% of available memory...
	Warning: Reducing model 'n_estimators' from 226 -> 152 due to low time. Expected time usage reduced from 472.1s -> 318.4s...
	-80.9917	 = Validation score   (-mean_absolute_error)
	181.83s	 = Training   runtime
	0.8s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 131.41s of the 330.78s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 402.
	Ran out of time, early stopping on iteration 411.
	Ran out of time, early stopping on iteration 421.
	Ran out of time, early stopping on iteration 447.
	-61.9402	 = Validation score   (-mean_absolute_error)
	94.46s	 = Training   runtime
	0.31s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 35.92s of the 235.29s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.2 GB
	Warning: Reducing model 'n_estimators' from 300 -> 233 due to low memory. Expected memory usage reduced from 19.3% -> 15.0% of available memory...
	Warning: Reducing model 'n_estimators' from 233 -> 42 due to low time. Expected time usage reduced from 193.5s -> 35.5s...
	-81.2182	 = Validation score   (-mean_absolute_error)
	24.65s	 = Training   runtime
	0.26s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 9.26s of the 208.63s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Time limit exceeded... Skipping NeuralNetFastAI_BAG_L1.
Fitting model: XGBoost_BAG_L1 ... Training model for up to 5.20s of the 204.57s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Time limit exceeded... Skipping XGBoost_BAG_L1.
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 3.38s of the 202.75s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 195.85s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/3.0 GB
	Ensemble Weights: {'CatBoost_BAG_L1': 1.0}
	-61.9402	 = Validation score   (-mean_absolute_error)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 195.72s of the 195.57s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-76.5781	 = Validation score   (-mean_absolute_error)
	29.33s	 = Training   runtime
	0.85s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 164.51s of the 164.36s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-76.5038	 = Validation score   (-mean_absolute_error)
	33.4s	 = Training   runtime
	0.85s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 129.12s of the 128.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.1 GB
	Warning: Reducing model 'n_estimators' from 300 -> 231 due to low memory. Expected memory usage reduced from 19.43% -> 15.0% of available memory...
	Warning: Reducing model 'n_estimators' from 231 -> 43 due to low time. Expected time usage reduced from 685.1s -> 128.6s...
	-79.7165	 = Validation score   (-mean_absolute_error)
	81.55s	 = Training   runtime
	0.26s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 45.56s of the 45.41s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 128.
	Ran out of time, early stopping on iteration 130.
	Ran out of time, early stopping on iteration 135.
	Ran out of time, early stopping on iteration 140.
	Ran out of time, early stopping on iteration 139.
	Ran out of time, early stopping on iteration 162.
	Ran out of time, early stopping on iteration 171.
	Ran out of time, early stopping on iteration 218.
	-61.8712	 = Validation score   (-mean_absolute_error)
	43.08s	 = Training   runtime
	0.28s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 1.07s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/3.3 GB
	Ensemble Weights: {'CatBoost_BAG_L2': 0.96, 'CatBoost_BAG_L1': 0.04}
	-61.8712	 = Validation score   (-mean_absolute_error)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 599.25s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 6144.3 rows/s (23319 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_082456")

                     model  score_test  score_val          eval_metric  \
0      WeightedEnsemble_L3  -61.871162 -61.871162  mean_absolute_error
1          CatBoost_BAG_L2  -61.871164 -61.871164  mean_absolute_error
2          CatBoost_BAG_L1  -61.940182 -61.940182  mean_absolute_error
3      WeightedEnsemble_L2  -61.940182 -61.940182  mean_absolute_error
4        LightGBMXT_BAG_L1  -76.457967 -76.457967  mean_absolute_error
5          LightGBM_BAG_L2  -76.503808 -76.503808  mean_absolute_error
6          LightGBM_BAG_L1  -76.536910 -76.536910  mean_absolute_error
7        LightGBMXT_BAG_L2  -76.578117 -76.578117  mean_absolute_error
8   RandomForestMSE_BAG_L2  -79.716494 -79.716494  mean_absolute_error
9   RandomForestMSE_BAG_L1  -80.991696 -80.991696  mean_absolute_error
10    ExtraTreesMSE_BAG_L1  -81.218155 -81.218155  mean_absolute_error

    pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  \
0         3.009381       3.795198  416.782770                 0.034235
1         2.975146       3.793834  416.654430                 0.145421
2         0.153694       0.310717   94.456693                 0.153694
3         0.186232       0.311839   94.530355                 0.032538
4         0.821664       1.217169   40.585756                 0.821664
5         3.431553       4.359017  406.970892                 0.601828
6         0.692378       0.926718   32.054362                 0.692378
7         3.395188       4.362458  402.902222                 0.565463
8         3.109004       3.773882  455.116239                 0.279278
9         0.937118       0.801641  181.826581                 0.937118
10        0.224872       0.257320   24.646348                 0.224872

    pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
0                 0.001364           0.128340            3       True
1                 0.280268          43.084690            2       True
2                 0.310717          94.456693            1       True
3                 0.001123           0.073662            2       True
4                 1.217169          40.585756            1       True
5                 0.845451          33.401152            2       True
6                 0.926718          32.054362            1       True
7                 0.848891          29.332481            2       True
8                 0.260316          81.546499            2       True
9                 0.801641         181.826581            1       True
10                0.257320          24.646348            1       True

    fit_order
0          11
1          10
2           4
3           6
4           1
5           8
6           2
7           7
8           9
9           3
10          5

In [12]:
importance = predictor.feature_importance(val_ag)
print(importance.head(20))

These features in provided data are not utilized by the predictor and will be ignored: ['monetary_per_item', 'avg_items_per_sale']
Computing feature importance via permutation shuffling for 84 features using 5000 rows with 5 shuffle sets...
	635.87s	= Expected runtime (127.17s per shuffle set)
	184.7s	= Actual runtime (Completed 5 of 5 shuffle sets)

                            importance    stddev   p_value  n  p99_high  \
recency_ratio                 0.325225  0.100762  0.000977  5  0.532694
total_revenue_net             0.303899  0.136777  0.003831  5  0.585524
prob_alive                    0.276692  0.135227  0.005110  5  0.555126
pred_num_purchases            0.267828  0.106309  0.002443  5  0.486721
n_sales                       0.233568  0.082516  0.001595  5  0.403470
avg_days_between_orders       0.231933  0.022124  0.000010  5  0.277486
purchase_frequency            0.195632  0.055387  0.000695  5  0.309674
avg_days_between_purchases    0.194705  0.069132  0.001624  5  0.337049
customer_lifetime_days        0.191969  0.070226  0.001813  5  0.336566
n_items                       0.146699  0.033819  0.000316  5  0.216332
last_purchase                 0.133278  0.078662  0.009646  5  0.295245
max_days_between_orders       0.120016  0.023966  0.000181  5  0.169363
avg_revenue_per_day_total     0.111813  0.040744  0.001787  5  0.195706
std_days_between_orders       0.099991  0.021847  0.000257  5  0.144974
recency_days                  0.089600  0.046887  0.006459  5  0.186142
prod_type_3_n_unique          0.080883  0.032132  0.002450  5  0.147043
size_min                      0.079789  0.051967  0.013229  5  0.186790
prod_type_5_n_unique          0.078834  0.045296  0.008833  5  0.172100
expected_avg_sales            0.073048  0.044587  0.010757  5  0.164853
n_sales_non_returned          0.071755  0.053074  0.019522  5  0.181035

                             p99_low
recency_ratio               0.117755
total_revenue_net           0.022274
prob_alive                 -0.001742
pred_num_purchases          0.048935
n_sales                     0.063667
avg_days_between_orders     0.186380
purchase_frequency          0.081590
avg_days_between_purchases  0.052361
customer_lifetime_days      0.047373
n_items                     0.077066
last_purchase              -0.028689
max_days_between_orders     0.070669
avg_revenue_per_day_total   0.027920
std_days_between_orders     0.055009
recency_days               -0.006941
prod_type_3_n_unique        0.014723
size_min                   -0.027211
prod_type_5_n_unique       -0.014431
expected_avg_sales         -0.018756
n_sales_non_returned       -0.037526

In [ ]:
# Voorspel op de validatieset
y_val_true = val_set["revenue_2018_2019"]
y_val_pred = predictor.predict(val_ag.drop(columns=["revenue_2018_2019"]))

# Bereken metrieken
mae_val = mean_absolute_error(y_val_true, y_val_pred)
spearman_val, _ = spearmanr(y_val_true, y_val_pred)

autogluon_metrics = pd.DataFrame([
    {
        "model_name": "AutoGluon",
        "AUC": np.nan,
        "MAE": mae_val,
        "Spearman": spearman_val
    }
])
autogluon_metrics.to_csv("autogluon_model_comparison.csv", index=False)

print(f"Validatie MAE: {mae_val}")
print(f"Validatie Spearman: {spearman_val}")
print("AutoGluon metrics saved to autogluon_model_comparison.csv")

Validatie MAE: 61.871162078885106
Validatie Spearman: 0.3771454133066694
AutoGluon metrics saved to autogluon_model_comparison.csv

In [14]:
# Submission maken met AutoGluon predictions op de test set

autogluon_pred_test = predictor.predict(X_test_ag)
autogluon_pred_test = np.clip(autogluon_pred_test, 0, None)

submission = pd.DataFrame({
    "cust_id": test_cust_ids,
    "predicted_revenue_2018_2019": autogluon_pred_test
})

submission_name = "submission_autogluon.csv"
submission.to_csv(submission_name, index=False)

print("Saved:", submission_name)
print("Prediction summary")
print("min :", autogluon_pred_test.min())
print("max :", autogluon_pred_test.max())
print("mean:", autogluon_pred_test.mean())

submission.head()

Saved: submission_autogluon.csv
Prediction summary
min : 0.0
max : 428.66693
mean: 25.655182

            cust_id  predicted_revenue_2018_2019
0  2dfoualegmpt6x2h                 3.272733e+02
1  d2q2stjpnzld7a4r                 3.859248e+01
2  cojscuqlpylhclv2                 3.970849e-07
3  vntezlhi2ryvxk6m                 1.208980e+02
4  jgy4ytjkdr2b75wf                 1.294462e+02

In [15]:
# Log-variant voorbereiden

train_ag_log = train_ag.copy()
val_ag_log = val_ag.copy()

train_ag_log["revenue_2018_2019"] = np.log1p(train_ag_log["revenue_2018_2019"])
val_ag_log["revenue_2018_2019"] = np.log1p(val_ag_log["revenue_2018_2019"])

def safe_spearman(y_true, y_pred):
    corr, _ = spearmanr(y_true, y_pred)
    return 0.0 if pd.isna(corr) else corr

X_val_ag = val_ag.drop(columns=["revenue_2018_2019"]).copy()
y_val_true = val_ag["revenue_2018_2019"].copy()

In [16]:
# AutoGluon trainen op log1p(target)
# Verhoog time_limit als je de log-variant langer wilt laten zoeken.

predictor_log = TabularPredictor(
    label="revenue_2018_2019",
    eval_metric="mean_absolute_error",
).fit(
    train_data=train_ag_log,
    tuning_data=val_ag_log,
    use_bag_holdout=True,
    presets="best_quality",
    time_limit=3600
)

print(predictor_log.leaderboard(val_ag_log))

No path specified. Models will be saved in: "AutogluonModels\ag-20260425_083903"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.2
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          12
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.16 GB / 15.72 GB (20.1%)
Disk Space Avail:   150.90 GB / 475.28 GB (31.7%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to False. Reason: Skip dynamic_stacking when use_bag_holdout is enabled. (use_bag_holdout=True)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_083903"
Train Data Rows:    93272
Train Data Columns: 86
Tuning Data Rows:    23319
Tuning Data Columns: 86
Label Column:       revenue_2018_2019
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (7.089193112073969, 0.0, 1.79312, 2.41659)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3155.29 MB
	Train Data (Original)  Memory Usage: 87.84 MB (2.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 2): ['monetary_per_item', 'avg_items_per_sale']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 2 | ['monetary_per_item', 'avg_items_per_sale']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                        : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('object', ['datetime_as_object']) :  2 | ['first_purchase', 'last_purchase']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                  : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('int', ['datetime_as_int']) : 10 | ['first_purchase', 'first_purchase.year', 'first_purchase.month', 'first_purchase.day', 'first_purchase.dayofweek', ...]
	1.7s = Fit runtime
	84 features in original data used to generate 92 features in processed data.
	Train Data (Processed) Memory Usage: 81.84 MB (2.6% of available memory)
Data preprocessing and feature engineering runtime = 2.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2398.04s of the 3597.95s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.8566	 = Validation score   (-mean_absolute_error)
	44.86s	 = Training   runtime
	1.28s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 2350.43s of the 3550.34s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.8594	 = Validation score   (-mean_absolute_error)
	44.76s	 = Training   runtime
	1.18s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 2303.11s of the 3503.02s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.0 GB
	Warning: Reducing model 'n_estimators' from 300 -> 220 due to low memory. Expected memory usage reduced from 20.4% -> 15.0% of available memory...
	-1.8925	 = Validation score   (-mean_absolute_error)
	221.78s	 = Training   runtime
	1.17s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 2073.18s of the 3273.08s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.4498	 = Validation score   (-mean_absolute_error)
	121.6s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 1950.39s of the 3150.30s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.2 GB
	Warning: Reducing model 'n_estimators' from 300 -> 234 due to low memory. Expected memory usage reduced from 19.2% -> 15.0% of available memory...
	-1.8774	 = Validation score   (-mean_absolute_error)
	118.52s	 = Training   runtime
	1.42s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 1821.94s of the 3021.85s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
No improvement since epoch 3: early stopping
No improvement since epoch 9: early stopping
	-1.7931	 = Validation score   (-mean_absolute_error)
	1211.02s	 = Training   runtime
	15.56s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 591.45s of the 1791.36s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.8541	 = Validation score   (-mean_absolute_error)
	65.63s	 = Training   runtime
	1.98s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 521.91s of the 1721.82s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 7)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 7)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 7)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 9)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 12)
	-1.4328	 = Validation score   (-mean_absolute_error)
	495.35s	 = Training   runtime
	5.19s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 17.69s of the 1217.60s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 27. Best iteration is:
	[27]	valid_set's l1: 2.04122
	Ran out of time, early stopping on iteration 27. Best iteration is:
	[27]	valid_set's l1: 2.04249
	Ran out of time, early stopping on iteration 23. Best iteration is:
	[23]	valid_set's l1: 2.06117
	Ran out of time, early stopping on iteration 25. Best iteration is:
	[25]	valid_set's l1: 2.05191
	Ran out of time, early stopping on iteration 33. Best iteration is:
	[33]	valid_set's l1: 2.02077
	Ran out of time, early stopping on iteration 32. Best iteration is:
	[32]	valid_set's l1: 2.02174
	Ran out of time, early stopping on iteration 36. Best iteration is:
	[36]	valid_set's l1: 1.99924
	Ran out of time, early stopping on iteration 50. Best iteration is:
	[50]	valid_set's l1: 1.94794
	-2.0197	 = Validation score   (-mean_absolute_error)
	16.25s	 = Training   runtime
	0.6s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1199.47s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/2.9 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 1.0}
	-1.4328	 = Validation score   (-mean_absolute_error)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 1199.21s of the 1199.01s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.8559	 = Validation score   (-mean_absolute_error)
	35.82s	 = Training   runtime
	1.07s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 1161.13s of the 1160.93s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)

[1000]	valid_set's l1: 1.85344
[2000]	valid_set's l1: 1.84744
[3000]	valid_set's l1: 1.84482
[4000]	valid_set's l1: 1.84288
[5000]	valid_set's l1: 1.84072
[6000]	valid_set's l1: 1.84056
[7000]	valid_set's l1: 1.83844
[8000]	valid_set's l1: 1.83927
[9000]	valid_set's l1: 1.83839
[10000]	valid_set's l1: 1.83761

	-1.8562	 = Validation score   (-mean_absolute_error)
	152.12s	 = Training   runtime
	8.35s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 994.99s of the 994.79s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.5 GB
	Warning: Reducing model 'n_estimators' from 300 -> 264 due to low memory. Expected memory usage reduced from 17.04% -> 15.0% of available memory...
	-1.8782	 = Validation score   (-mean_absolute_error)
	441.41s	 = Training   runtime
	2.08s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 540.92s of the 540.72s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.4401	 = Validation score   (-mean_absolute_error)
	68.41s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 471.15s of the 470.95s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.3 GB
	Warning: Reducing model 'n_estimators' from 300 -> 236 due to low memory. Expected memory usage reduced from 19.03% -> 15.0% of available memory...
	-1.8831	 = Validation score   (-mean_absolute_error)
	142.06s	 = Training   runtime
	1.04s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 320.74s of the 320.54s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 5)
	-1.7854	 = Validation score   (-mean_absolute_error)
	287.74s	 = Training   runtime
	4.83s	 = Validation runtime
Fitting model: XGBoost_BAG_L2 ... Training model for up to 25.01s of the 24.81s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-1.8598	 = Validation score   (-mean_absolute_error)
	22.81s	 = Training   runtime
	1.88s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -1.91s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/2.8 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 1.0}
	-1.4328	 = Validation score   (-mean_absolute_error)
	0.3s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 3602.42s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4490.5 rows/s (23319 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_083903")

                     model  score_test  score_val          eval_metric  \
0    NeuralNetTorch_BAG_L1   -1.432830  -1.432830  mean_absolute_error
1      WeightedEnsemble_L2   -1.432830  -1.432830  mean_absolute_error
2      WeightedEnsemble_L3   -1.432830  -1.432830  mean_absolute_error
3          CatBoost_BAG_L2   -1.440132  -1.440132  mean_absolute_error
4          CatBoost_BAG_L1   -1.449809  -1.449809  mean_absolute_error
5   NeuralNetFastAI_BAG_L2   -1.785423  -1.785423  mean_absolute_error
6   NeuralNetFastAI_BAG_L1   -1.793065  -1.793065  mean_absolute_error
7           XGBoost_BAG_L1   -1.854120  -1.854120  mean_absolute_error
8        LightGBMXT_BAG_L2   -1.855943  -1.855943  mean_absolute_error
9          LightGBM_BAG_L2   -1.856166  -1.856166  mean_absolute_error
10       LightGBMXT_BAG_L1   -1.856569  -1.856569  mean_absolute_error
11         LightGBM_BAG_L1   -1.859360  -1.859360  mean_absolute_error
12          XGBoost_BAG_L2   -1.859838  -1.859838  mean_absolute_error
13    ExtraTreesMSE_BAG_L1   -1.877426  -1.877426  mean_absolute_error
14  RandomForestMSE_BAG_L2   -1.878157  -1.878157  mean_absolute_error
15    ExtraTreesMSE_BAG_L2   -1.883082  -1.883082  mean_absolute_error
16  RandomForestMSE_BAG_L1   -1.892488  -1.892488  mean_absolute_error
17    LightGBMLarge_BAG_L1   -2.019685  -2.019685  mean_absolute_error

    pred_time_test  pred_time_val     fit_time  pred_time_test_marginal  \
0         4.082733       5.191637   495.350452                 4.082733
1         4.114476       5.192964   495.558674                 0.031743
2         4.117450       5.193571   495.648038                 0.034717
3        17.115049      28.985012  2408.183223                 0.204890
4         0.313608       0.297992   121.604917                 0.313608
5        21.424072      33.509255  2627.510335                 4.513913
6         5.237353      15.558884  1211.019914                 5.237353
7         1.609819       1.977752    65.629374                 1.609819
8        17.604476      29.753657  2375.589565                 0.694317
9        23.915088      37.027604  2491.897382                 7.004929
10        1.480917       1.279724    44.864524                 1.480917
11        1.244985       1.182196    44.755810                 1.244985
12       18.225842      30.561344  2362.583915                 1.315683
13        1.314538       1.418803   118.518277                 1.314538
14       18.409152      30.759311  2781.180943                 1.498992
15       18.272428      29.725488  2481.834680                 1.362269
16        1.323797       1.172959   221.782432                 1.323797
17        0.302409       0.601889    16.247603                 0.302409

    pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
0                 5.191637         495.350452            1       True
1                 0.001327           0.208221            2       True
2                 0.001934           0.297585            3       True
3                 0.303175          68.409920            2       True
4                 0.297992         121.604917            1       True
5                 4.827419         287.737032            2       True
6                15.558884        1211.019914            1       True
7                 1.977752          65.629374            1       True
8                 1.071820          35.816262            2       True
9                 8.345767         152.124079            2       True
10                1.279724          44.864524            1       True
11                1.182196          44.755810            1       True
12                1.879507          22.810612            2       True
13                1.418803         118.518277            1       True
14                2.077474         441.407640            2       True
15                1.043652         142.061377            2       True
16                1.172959         221.782432            1       True
17                0.601889          16.247603            1       True

    fit_order
0           8
1          10
2          18
3          14
4           4
5          16
6           6
7           7
8          11
9          12
10          1
11          2
12         17
13          5
14         13
15         15
16          3
17          9

In [17]:
# Evaluatie van baseline en log-variant op originele schaal

y_val_pred_base = np.clip(np.asarray(predictor.predict(X_val_ag)), 0, None)
y_val_pred_log = np.expm1(predictor_log.predict(X_val_ag))
y_val_pred_log = np.clip(np.asarray(y_val_pred_log), 0, None)

mae_base = mean_absolute_error(y_val_true, y_val_pred_base)
sp_base, _ = spearmanr(y_val_true, y_val_pred_base)

mae_log = mean_absolute_error(y_val_true, y_val_pred_log)
sp_log, _ = spearmanr(y_val_true, y_val_pred_log)

comparison_df = pd.DataFrame([
    {"model_name": "AutoGluon_base", "MAE": mae_base, "Spearman": sp_base},
    {"model_name": "AutoGluon_log1p", "MAE": mae_log, "Spearman": sp_log}
])

comparison_df.to_csv("autogluon_log_model_comparison.csv", index=False)
comparison_df

        model_name        MAE  Spearman
0   AutoGluon_base  61.870484  0.377204
1  AutoGluon_log1p  61.856358  0.395572

In [18]:
# Zoek de beste ensemble-gewichten op de validatieset

rows = []

for weight_log in np.arange(0.0, 1.001, 0.05):
    weight_base = 1.0 - weight_log
    pred_ensemble = weight_base * y_val_pred_base + weight_log * y_val_pred_log

    rows.append({
        "weight_base": round(weight_base, 2),
        "weight_log": round(weight_log, 2),
        "MAE": mean_absolute_error(y_val_true, pred_ensemble),
        "Spearman": safe_spearman(y_val_true, pred_ensemble)
    })

ensemble_search = pd.DataFrame(rows)
best_mae_row = ensemble_search.sort_values(["MAE", "Spearman"], ascending=[True, False]).iloc[0]
best_spearman_row = ensemble_search.sort_values(["Spearman", "MAE"], ascending=[False, True]).iloc[0]

print("Best ensemble by MAE")
print(best_mae_row)
print()
print("Best ensemble by Spearman")
print(best_spearman_row)

ensemble_search.sort_values("MAE").head(10)

Best ensemble by MAE
weight_base     0.500000
weight_log      0.500000
MAE            61.788205
Spearman        0.378232
Name: 10, dtype: float64

Best ensemble by Spearman
weight_base     0.000000
weight_log      1.000000
MAE            61.856358
Spearman        0.395572
Name: 20, dtype: float64

    weight_base  weight_log        MAE  Spearman
10         0.50        0.50  61.788205  0.378232
11         0.45        0.55  61.788933  0.378317
9          0.55        0.45  61.789805  0.378084
12         0.40        0.60  61.791660  0.378350
8          0.60        0.40  61.792541  0.377956
13         0.35        0.65  61.795530  0.378348
7          0.65        0.35  61.796680  0.377765
14         0.30        0.70  61.800409  0.378371
6          0.70        0.30  61.802455  0.377573
15         0.25        0.75  61.806501  0.378435

In [19]:
# Verfijn rond de beste MAE-gewichten

start_log = max(0, best_mae_row["weight_log"] - 0.05)
end_log = min(1, best_mae_row["weight_log"] + 0.05)

fine_rows = []

for weight_log in np.arange(start_log, end_log + 0.001, 0.01):
    weight_base = 1.0 - weight_log
    pred_ensemble = weight_base * y_val_pred_base + weight_log * y_val_pred_log

    fine_rows.append({
        "weight_base": round(weight_base, 2),
        "weight_log": round(weight_log, 2),
        "MAE": mean_absolute_error(y_val_true, pred_ensemble),
        "Spearman": safe_spearman(y_val_true, pred_ensemble)
    })

ensemble_search_fine = pd.DataFrame(fine_rows)
final_ensemble_row = ensemble_search_fine.sort_values(["MAE", "Spearman"], ascending=[True, False]).iloc[0]

final_weight_base = float(final_ensemble_row["weight_base"])
final_weight_log = float(final_ensemble_row["weight_log"])
y_val_pred_ensemble = final_weight_base * y_val_pred_base + final_weight_log * y_val_pred_log

mae_ensemble = mean_absolute_error(y_val_true, y_val_pred_ensemble)
sp_ensemble, _ = spearmanr(y_val_true, y_val_pred_ensemble)

print("Final best ensemble")
print("Weight base:", final_weight_base)
print("Weight log :", final_weight_log)
print("Validation MAE     :", mae_ensemble)
print("Validation Spearman:", sp_ensemble)

Final best ensemble
Weight base: 0.49
Weight log : 0.51
Validation MAE     : 61.78816813301773
Validation Spearman: 0.3782576020685911

In [20]:
# Overzicht opslaan

comparison_with_ensemble = pd.DataFrame([
    {"model_name": "AutoGluon_base", "MAE": mae_base, "Spearman": sp_base},
    {"model_name": "AutoGluon_log1p", "MAE": mae_log, "Spearman": sp_log},
    {"model_name": "AutoGluon_base_log_ensemble", "MAE": mae_ensemble, "Spearman": sp_ensemble}
])

comparison_with_ensemble.to_csv("autogluon_log_ensemble_comparison.csv", index=False)
comparison_with_ensemble.sort_values("MAE")

                    model_name        MAE  Spearman
2  AutoGluon_base_log_ensemble  61.788168  0.378258
1              AutoGluon_log1p  61.856358  0.395572
0               AutoGluon_base  61.870484  0.377204

In [ ]:
# Submission voor de log-variant

autogluon_log_pred_test = np.expm1(predictor_log.predict(X_test_ag))
autogluon_log_pred_test = np.clip(np.asarray(autogluon_log_pred_test), 0, None)

submission_log = pd.DataFrame({
    "cust_id": test_cust_ids,
    "predicted_revenue_2018_2019": autogluon_log_pred_test
})

submission_log_name = "submission_autogluon_log.csv"
submission_log.to_csv(submission_log_name, index=False)

print("Saved:", submission_log_name)
print("Prediction summary")
print("min :", autogluon_log_pred_test.min())
print("max :", autogluon_log_pred_test.max())
print("mean:", autogluon_log_pred_test.mean())

submission_log.head()

In [ ]:
# Submission voor het beste ensemble volgens validatie-MAE

autogluon_base_pred_test = np.clip(np.asarray(predictor.predict(X_test_ag)), 0, None)
autogluon_log_pred_test = np.expm1(predictor_log.predict(X_test_ag))
autogluon_log_pred_test = np.clip(np.asarray(autogluon_log_pred_test), 0, None)

autogluon_ensemble_pred_test = final_weight_base * autogluon_base_pred_test + final_weight_log * autogluon_log_pred_test
autogluon_ensemble_pred_test = np.clip(autogluon_ensemble_pred_test, 0, None)

submission_ensemble = pd.DataFrame({
    "cust_id": test_cust_ids,
    "predicted_revenue_2018_2019": autogluon_ensemble_pred_test
})

submission_ensemble_name = "submission_autogluon_log_ensemble.csv"
submission_ensemble.to_csv(submission_ensemble_name, index=False)

print("Saved:", submission_ensemble_name)
print("Prediction summary")
print("min :", autogluon_ensemble_pred_test.min())
print("max :", autogluon_ensemble_pred_test.max())
print("mean:", autogluon_ensemble_pred_test.mean())

submission_ensemble.head()

In [21]:
# Two-stage data voorbereiden: classifier voor buyer en regressor voor amount

train_cls = train_ag.copy()
val_cls = val_ag.copy()

train_cls["is_buyer"] = (train_cls["revenue_2018_2019"] > 0).astype(int)
val_cls["is_buyer"] = (val_cls["revenue_2018_2019"] > 0).astype(int)

train_cls = train_cls.drop(columns=["revenue_2018_2019"])
val_cls = val_cls.drop(columns=["revenue_2018_2019"])

train_buyers = train_ag[train_ag["revenue_2018_2019"] > 0].copy()
val_buyers = val_ag[val_ag["revenue_2018_2019"] > 0].copy()

train_buyers_log = train_buyers.copy()
val_buyers_log = val_buyers.copy()
train_buyers_log["revenue_2018_2019"] = np.log1p(train_buyers_log["revenue_2018_2019"])
val_buyers_log["revenue_2018_2019"] = np.log1p(val_buyers_log["revenue_2018_2019"])

X_val_cls = val_cls.drop(columns=["is_buyer"]).copy()
y_val_true = val_ag["revenue_2018_2019"].copy()
y_val_is_buyer = (y_val_true > 0).astype(int)

In [25]:
# AutoGluon classifier voor P(revenue > 0)

predictor_cls = TabularPredictor(
    label="is_buyer",
    problem_type="binary",
    eval_metric="roc_auc",
).fit(
    train_data=train_cls,
    tuning_data=val_cls,
    use_bag_holdout=True,
    presets="best_quality",
    time_limit=1800
)

print(predictor_cls.leaderboard(val_cls))

No path specified. Models will be saved in: "AutogluonModels\ag-20260425_102609"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.2
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          12
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.70 GB / 15.72 GB (23.5%)
Disk Space Avail:   142.47 GB / 475.28 GB (30.0%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to False. Reason: Skip dynamic_stacking when use_bag_holdout is enabled. (use_bag_holdout=True)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_102609"
Train Data Rows:    93272
Train Data Columns: 86
Tuning Data Rows:    23319
Tuning Data Columns: 86
Label Column:       is_buyer
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3717.01 MB
	Train Data (Original)  Memory Usage: 87.84 MB (2.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 2): ['monetary_per_item', 'avg_items_per_sale']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 2 | ['monetary_per_item', 'avg_items_per_sale']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                        : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('object', ['datetime_as_object']) :  2 | ['first_purchase', 'last_purchase']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                  : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('int', ['datetime_as_int']) : 10 | ['first_purchase', 'first_purchase.year', 'first_purchase.month', 'first_purchase.day', 'first_purchase.dayofweek', ...]
	1.8s = Fit runtime
	84 features in original data used to generate 92 features in processed data.
	Train Data (Processed) Memory Usage: 81.84 MB (2.2% of available memory)
Data preprocessing and feature engineering runtime = 2.28s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 108 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1198.18s of the 1797.70s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7279	 = Validation score   (roc_auc)
	27.9s	 = Training   runtime
	1.13s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1167.56s of the 1767.08s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7276	 = Validation score   (roc_auc)
	24.13s	 = Training   runtime
	1.0s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 1140.73s of the 1740.25s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/4.0 GB
	Warning: Reducing model 'n_estimators' from 300 -> 267 due to low memory. Expected memory usage reduced from 16.81% -> 15.0% of available memory...
	0.7124	 = Validation score   (roc_auc)
	32.75s	 = Training   runtime
	1.66s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 1094.90s of the 1694.42s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.8 GB
	Warning: Reducing model 'n_estimators' from 300 -> 250 due to low memory. Expected memory usage reduced from 17.96% -> 15.0% of available memory...
	0.7131	 = Validation score   (roc_auc)
	297.84s	 = Training   runtime
	8.04s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 744.20s of the 1343.72s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 89.
	Ran out of time, early stopping on iteration 259.
	0.7278	 = Validation score   (roc_auc)
	248.68s	 = Training   runtime
	0.3s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 490.62s of the 1090.14s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.9 GB
	Warning: Reducing model 'n_estimators' from 300 -> 255 due to low memory. Expected memory usage reduced from 17.62% -> 15.0% of available memory...
	0.7205	 = Validation score   (roc_auc)
	16.53s	 = Training   runtime
	1.5s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 462.66s of the 1062.18s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.5 GB
	Warning: Reducing model 'n_estimators' from 300 -> 233 due to low memory. Expected memory usage reduced from 19.31% -> 15.0% of available memory...
	0.7205	 = Validation score   (roc_auc)
	15.34s	 = Training   runtime
	1.39s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 436.69s of the 1036.21s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 6)
	Ran out of time, stopping training early. (Stopping on epoch 5)
	0.7266	 = Validation score   (roc_auc)
	391.47s	 = Training   runtime
	7.34s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 33.35s of the 632.87s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7276	 = Validation score   (roc_auc)
	22.8s	 = Training   runtime
	2.03s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 6.58s of the 606.10s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1.48s of the 601.00s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Warning: Model has no time left to train, skipping model... (Time Left = -0.1s)
	Time limit exceeded... Skipping LightGBMLarge_BAG_L1.
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 0.26s of the 599.78s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Time limit exceeded... Skipping CatBoost_r177_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 598.53s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/4.0 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.35, 'CatBoost_BAG_L1': 0.25, 'XGBoost_BAG_L1': 0.15, 'RandomForestEntr_BAG_L1': 0.1, 'NeuralNetFastAI_BAG_L1': 0.1, 'ExtraTreesGini_BAG_L1': 0.05}
	0.7288	 = Validation score   (roc_auc)
	1.36s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting 108 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 597.05s of the 596.78s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7285	 = Validation score   (roc_auc)
	22.31s	 = Training   runtime
	0.95s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 572.22s of the 571.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7284	 = Validation score   (roc_auc)
	22.43s	 = Training   runtime
	1.06s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 547.21s of the 546.94s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.9 GB
	Warning: Reducing model 'n_estimators' from 300 -> 259 due to low memory. Expected memory usage reduced from 17.35% -> 15.0% of available memory...
	0.7176	 = Validation score   (roc_auc)
	43.77s	 = Training   runtime
	1.92s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 489.59s of the 489.33s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.4 GB
	Warning: Reducing model 'n_estimators' from 300 -> 240 due to low memory. Expected memory usage reduced from 18.7% -> 15.0% of available memory...
	0.7192	 = Validation score   (roc_auc)
	59.67s	 = Training   runtime
	2.16s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 410.88s of the 410.61s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	0.7286	 = Validation score   (roc_auc)
	80.29s	 = Training   runtime
	0.7s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 328.17s of the 327.91s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.8 GB
	Warning: Reducing model 'n_estimators' from 300 -> 251 due to low memory. Expected memory usage reduced from 17.86% -> 15.0% of available memory...
	0.722	 = Validation score   (roc_auc)
	20.53s	 = Training   runtime
	2.23s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 287.43s of the 287.16s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.4/3.4 GB
	Warning: Reducing model 'n_estimators' from 300 -> 226 due to low memory. Expected memory usage reduced from 19.86% -> 15.0% of available memory...
	0.7234	 = Validation score   (roc_auc)
	19.11s	 = Training   runtime
	1.89s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 251.01s of the 250.75s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 1)
	Ran out of time, stopping training early. (Stopping on epoch 2)
	Ran out of time, stopping training early. (Stopping on epoch 2)
	Ran out of time, stopping training early. (Stopping on epoch 3)
	0.7275	 = Validation score   (roc_auc)
	211.24s	 = Training   runtime
	6.54s	 = Validation runtime
Fitting model: XGBoost_BAG_L2 ... Training model for up to 28.22s of the 27.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Time limit exceeded... Skipping XGBoost_BAG_L2.
Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 23.59s of the 23.33s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\.venv\Lib\site-packages\sklearn\compose\_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L2.
Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 14.86s of the 14.60s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1. Best iteration is:
	[1]	valid_set's binary_logloss: 0.651778
	Time limit exceeded... Skipping LightGBMLarge_BAG_L2.
Fitting model: CatBoost_r177_BAG_L2 ... Training model for up to 11.34s of the 11.08s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	Ran out of time, early stopping on iteration 1.
	Time limit exceeded... Skipping CatBoost_r177_BAG_L2.
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 8.07s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/4.0 GB
	Ensemble Weights: {'CatBoost_BAG_L2': 0.333, 'LightGBM_BAG_L2': 0.19, 'CatBoost_BAG_L1': 0.143, 'LightGBMXT_BAG_L2': 0.143, 'RandomForestEntr_BAG_L1': 0.048, 'NeuralNetFastAI_BAG_L1': 0.048, 'RandomForestEntr_BAG_L2': 0.048, 'ExtraTreesEntr_BAG_L2': 0.048}
	0.7289	 = Validation score   (roc_auc)
	4.62s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 1796.93s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 748.6 rows/s (23319 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_102609")

                      model  score_test  score_val eval_metric  \
0       WeightedEnsemble_L3    0.728899   0.728899     roc_auc
1       WeightedEnsemble_L2    0.728786   0.728786     roc_auc
2           CatBoost_BAG_L2    0.728644   0.728644     roc_auc
3         LightGBMXT_BAG_L2    0.728521   0.728521     roc_auc
4           LightGBM_BAG_L2    0.728431   0.728431     roc_auc
5         LightGBMXT_BAG_L1    0.727944   0.727944     roc_auc
6           CatBoost_BAG_L1    0.727755   0.727755     roc_auc
7           LightGBM_BAG_L1    0.727637   0.727637     roc_auc
8            XGBoost_BAG_L1    0.727556   0.727556     roc_auc
9    NeuralNetFastAI_BAG_L2    0.727471   0.727471     roc_auc
10   NeuralNetFastAI_BAG_L1    0.726580   0.726580     roc_auc
11    ExtraTreesEntr_BAG_L2    0.723359   0.723359     roc_auc
12    ExtraTreesGini_BAG_L2    0.721988   0.721988     roc_auc
13    ExtraTreesGini_BAG_L1    0.720489   0.720489     roc_auc
14    ExtraTreesEntr_BAG_L1    0.720484   0.720484     roc_auc
15  RandomForestEntr_BAG_L2    0.719160   0.719160     roc_auc
16  RandomForestGini_BAG_L2    0.717564   0.717564     roc_auc
17  RandomForestEntr_BAG_L1    0.713108   0.713108     roc_auc
18  RandomForestGini_BAG_L1    0.712432   0.712432     roc_auc

    pred_time_test  pred_time_val     fit_time  pred_time_test_marginal  \
0        24.935994      31.149715  1285.895180                 0.115829
1        14.262678      20.339745  1006.592230                 0.103475
2        19.337681      25.081875  1157.751090                 0.284241
3        19.703778      25.330709  1099.772352                 0.650339
4        19.668074      25.443357  1099.890176                 0.614634
5         1.038783       1.130734    27.903049                 1.038783
6         0.291024       0.299379   248.679190                 0.291024
7         0.674554       1.001084    24.125724                 0.674554
8         2.236644       2.028003    22.804944                 2.236644
9        26.128309      30.924598  1288.701010                 7.074870
10        6.192533       7.337701   391.474639                 6.192533
11       21.198700      26.279554  1096.568872                 2.145261
12       21.306714      26.616782  1097.992485                 2.253274
13        2.083389       1.497767    16.534958                 2.083389
14        2.029447       1.391406    15.344435                 2.029447
15       21.125691      26.543660  1137.130055                 2.072251
16       21.290428      26.304678  1121.224438                 2.236988
17        2.316829       8.039708   297.839770                 2.316829
18        2.190236       1.658962    32.752690                 2.190236

    pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
0                 0.009538           4.620230            3       True
1                 0.006452           1.355680            2       True
2                 0.697130          80.291691            2       True
3                 0.945965          22.312953            2       True
4                 1.058613          22.430777            2       True
5                 1.130734          27.903049            1       True
6                 0.299379         248.679190            1       True
7                 1.001084          24.125724            1       True
8                 2.028003          22.804944            1       True
9                 6.539853         211.241611            2       True
10                7.337701         391.474639            1       True
11                1.894809          19.109473            2       True
12                2.232037          20.533086            2       True
13                1.497767          16.534958            1       True
14                1.391406          15.344435            1       True
15                2.158916          59.670656            2       True
16                1.919934          43.765039            2       True
17                8.039708         297.839770            1       True
18                1.658962          32.752690            1       True

    fit_order
0          19
1          10
2          15
3          11
4          12
5           1
6           5
7           2
8           9
9          18
10          8
11         17
12         16
13          6
14          7
15         14
16         13
17          4
18          3

In [26]:
# AutoGluon regressor enkel op buyers, getraind op log1p(amount)

predictor_buyers = TabularPredictor(
    label="revenue_2018_2019",
    eval_metric="mean_absolute_error",
).fit(
    train_data=train_buyers_log,
    tuning_data=val_buyers_log,
    use_bag_holdout=True,
    presets="best_quality",
    time_limit=3600
)

print(predictor_buyers.leaderboard(val_buyers_log))

No path specified. Models will be saved in: "AutogluonModels\ag-20260425_105645"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.2
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          12
Pytorch Version:    2.9.1+cpu
CUDA Version:       CUDA is not available
Memory Avail:       3.96 GB / 15.72 GB (25.2%)
Disk Space Avail:   137.96 GB / 475.28 GB (29.0%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to False. Reason: Skip dynamic_stacking when use_bag_holdout is enabled. (use_bag_holdout=True)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_105645"
Train Data Rows:    34126
Train Data Columns: 86
Tuning Data Rows:    8532
Tuning Data Columns: 86
Label Column:       revenue_2018_2019
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (7.089193112073969, 0.009950330853168083, 4.90089, 0.85462)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3987.24 MB
	Train Data (Original)  Memory Usage: 32.14 MB (0.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 2): ['monetary_per_item', 'avg_items_per_sale']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 2 | ['monetary_per_item', 'avg_items_per_sale']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                        : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('object', ['datetime_as_object']) :  2 | ['first_purchase', 'last_purchase']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 67 | ['n_items_non_returned', 'n_sales_non_returned', 'total_revenue_net', 'total_discount', 'total_revenue_gross', ...]
		('int', [])                  : 15 | ['n_items', 'n_sales', 'n_returns', 'customer_lifetime_days', 'recency_days', ...]
		('int', ['datetime_as_int']) : 10 | ['first_purchase', 'first_purchase.year', 'first_purchase.month', 'first_purchase.day', 'first_purchase.dayofweek', ...]
	1.2s = Fit runtime
	84 features in original data used to generate 92 features in processed data.
	Train Data (Processed) Memory Usage: 29.94 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 1.55s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2398.36s of the 3598.42s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.6305	 = Validation score   (-mean_absolute_error)
	22.04s	 = Training   runtime
	1.07s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 2374.13s of the 3574.18s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=10, gpus=0)
	-0.6313	 = Validation score   (-mean_absolute_error)
	21.24s	 = Training   runtime
	0.94s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 2350.92s of the 3550.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=12, gpus=0, mem=0.2/4.3 GB
	-0.6409	 = Validation score   (-mean_absolute_error)
	4218.19s	 = Training   runtime
	1.85s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the -677.27s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/3.2 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	-0.6305	 = Validation score   (-mean_absolute_error)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the -677.93s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=12, gpus=0, mem=0.0/3.1 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	-0.6305	 = Validation score   (-mean_absolute_error)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 4278.18s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7976.8 rows/s (8532 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("c:\Users\Marte\Documents\SCHOOL\2024_2026_KUL\2025-2026\SEMESTER 2\Advanced Analytics in a Big Data World\Assignment1\BigData_assignment1\AutogluonModels\ag-20260425_105645")

                    model  score_test  score_val          eval_metric  \
0       LightGBMXT_BAG_L1   -0.630518  -0.630518  mean_absolute_error
1     WeightedEnsemble_L3   -0.630518  -0.630518  mean_absolute_error
2     WeightedEnsemble_L2   -0.630518  -0.630518  mean_absolute_error
3         LightGBM_BAG_L1   -0.631279  -0.631279  mean_absolute_error
4  RandomForestMSE_BAG_L1   -0.640931  -0.640931  mean_absolute_error

   pred_time_test  pred_time_val     fit_time  pred_time_test_marginal  \
0        0.395365       1.067187    22.038187                 0.395365
1        0.434760       1.069578    22.150553                 0.039395
2        0.435544       1.069602    22.158854                 0.040179
3        0.262971       0.935515    21.241397                 0.262971
4        1.818734       1.854088  4218.192598                 1.818734

   pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
0                1.067187          22.038187            1       True
1                0.002391           0.112366            3       True
2                0.002415           0.120666            2       True
3                0.935515          21.241397            1       True
4                1.854088        4218.192598            1       True

   fit_order
0          1
1          5
2          4
3          2
4          3

In [28]:
# Two-stage validatie: soft combinatie en hard threshold search

proba_val_buy = predictor_cls.predict_proba(X_val_cls)[1]
pred_val_amount_buyers = np.expm1(predictor_buyers.predict(X_val_cls))
pred_val_amount_buyers = np.clip(np.asarray(pred_val_amount_buyers), 0, None)

pred_val_soft = np.clip(np.asarray(proba_val_buy) * pred_val_amount_buyers, 0, None)
mae_two_stage_soft = mean_absolute_error(y_val_true, pred_val_soft)
sp_two_stage_soft = safe_spearman(y_val_true, pred_val_soft)

threshold_rows = []
for threshold in np.arange(0.1, 0.91, 0.05):
    pred_val_hard = np.where(np.asarray(proba_val_buy) >= threshold, pred_val_amount_buyers, 0.0)
    threshold_rows.append({
        "threshold": round(float(threshold), 2),
        "MAE": mean_absolute_error(y_val_true, pred_val_hard),
        "Spearman": safe_spearman(y_val_true, pred_val_hard)
    })

threshold_results = pd.DataFrame(threshold_rows)
best_threshold_row = threshold_results.sort_values(["MAE", "Spearman"], ascending=[True, False]).iloc[0]
best_threshold = float(best_threshold_row["threshold"])
pred_val_hard_best = np.where(np.asarray(proba_val_buy) >= best_threshold, pred_val_amount_buyers, 0.0)

mae_two_stage_hard = mean_absolute_error(y_val_true, pred_val_hard_best)
sp_two_stage_hard = safe_spearman(y_val_true, pred_val_hard_best)

two_stage_results = pd.DataFrame([
    {"model_name": "TwoStage_soft", "MAE": mae_two_stage_soft, "Spearman": sp_two_stage_soft},
    {"model_name": "TwoStage_hard_threshold", "MAE": mae_two_stage_hard, "Spearman": sp_two_stage_hard, "threshold": best_threshold}
])

print("Soft two-stage")
print(two_stage_results.iloc[0])
print()
print("Best hard-threshold two-stage")
print(two_stage_results.iloc[1])

threshold_results.sort_values("MAE").head(10)

Soft two-stage
model_name    TwoStage_soft
MAE               71.348229
Spearman           0.408387
threshold               NaN
Name: 0, dtype: object

Best hard-threshold two-stage
model_name    TwoStage_hard_threshold
MAE                          63.02577
Spearman                     0.365703
threshold                        0.65
Name: 1, dtype: object

    threshold        MAE  Spearman
11       0.65  63.025770  0.365703
10       0.60  63.162600  0.384678
12       0.70  63.534621  0.339126
9        0.55  63.583954  0.400670
13       0.75  64.060268  0.315262
8        0.50  64.525408  0.415539
14       0.80  64.871646  0.283242
15       0.85  65.901043  0.240156
7        0.45  65.931340  0.420031
16       0.90  67.366023  0.185382

In [29]:
# Voeg two-stage toe aan het modeloverzicht

comparison_with_two_stage = pd.concat([
    comparison_with_ensemble,
    two_stage_results[["model_name", "MAE", "Spearman"]]
], ignore_index=True)

comparison_with_two_stage.to_csv("autogluon_full_comparison_with_twostage.csv", index=False)
comparison_with_two_stage.sort_values(["MAE", "Spearman"], ascending=[True, False])

                    model_name        MAE  Spearman
2  AutoGluon_base_log_ensemble  61.788168  0.378258
1              AutoGluon_log1p  61.856358  0.395572
0               AutoGluon_base  61.870484  0.377204
4      TwoStage_hard_threshold  63.025770  0.365703
3                TwoStage_soft  71.348229  0.408387

In [ ]:
# Submission voor de soft two-stage voorspelling

proba_test_buy = predictor_cls.predict_proba(X_test_ag)[1]
pred_test_amount_buyers = np.expm1(predictor_buyers.predict(X_test_ag))
pred_test_amount_buyers = np.clip(np.asarray(pred_test_amount_buyers), 0, None)

pred_test_soft = np.clip(np.asarray(proba_test_buy) * pred_test_amount_buyers, 0, None)

submission_two_stage_soft = pd.DataFrame({
    "cust_id": test_cust_ids,
    "predicted_revenue_2018_2019": pred_test_soft
})

submission_two_stage_soft_name = "submission_autogluon_two_stage_soft.csv"
submission_two_stage_soft.to_csv(submission_two_stage_soft_name, index=False)

print("Saved:", submission_two_stage_soft_name)
print("Prediction summary")
print("min :", pred_test_soft.min())
print("max :", pred_test_soft.max())
print("mean:", pred_test_soft.mean())

submission_two_stage_soft.head()

In [ ]:
# Submission voor de beste hard-threshold two-stage voorspelling

pred_test_hard = np.where(np.asarray(proba_test_buy) >= best_threshold, pred_test_amount_buyers, 0.0)
pred_test_hard = np.clip(np.asarray(pred_test_hard), 0, None)

submission_two_stage_hard = pd.DataFrame({
    "cust_id": test_cust_ids,
    "predicted_revenue_2018_2019": pred_test_hard
})

submission_two_stage_hard_name = "submission_autogluon_two_stage_hard.csv"
submission_two_stage_hard.to_csv(submission_two_stage_hard_name, index=False)

print("Saved:", submission_two_stage_hard_name)
print("Threshold:", best_threshold)
print("Prediction summary")
print("min :", pred_test_hard.min())
print("max :", pred_test_hard.max())
print("mean:", pred_test_hard.mean())

submission_two_stage_hard.head()